# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d0520d20c186d50a15925906f0c623f96e3f2d430c6f8c7183f0c6885c8d67e3ba3288216818074f092405b6bb624d66bc2d690a883dda51841cb24650eecd9

test:
  secret_key_base: abcc94a427213da0e5d2f3b8849ce16b194396cd446c100bab20045c05efe9dd2dae31312a8afc1a4e9d64de661b0c8194060e83ef59bb5ce47c265b50ed3c18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
